eduID.xcodeproj/project.pbxproj, eduID/Info.plist, eduID/Resources/Assets.xcassets/SecondaryColor.colorset/Contents.json, eduID/Theme.swift
TIQR-313: Add Deny button
TIQR-302: Update icons
=> TIQR-296: Set git release version

EduID/Flows/CreateEduID/ViewControllers/CreateEduIDFirstTimeDialogViewController.swift, EduID/Flows/CreateEduID/ViewModels/CreatePincodeAndBiometricAccessViewModel.swift
Fixed: flow 1: At 'connect school / institution' - the 'skip this' option is not functional.
=> EDURED-112

EduID/Flows/Scanning/VerifyScanResultViewController.swift, EduID/Localizable.swift, EduID/Resources/General/en.lproj/Localizable.strings, EduID/Resources/General/nl.lproj/Localizable.strings, EduID/SharedViews/EduIDButton.swift, EduID/Styling/UILabel+Styling.swift, EduID/Types/OnboardingManager.swift, EduID/localizations.yaml
=> EDURED-130: Added you are logged in

EduID/Flows/CreateEduID/ViewControllers/CreateEduIDExplanationViewController.swift, EduID/Flows/CreateEduID/ViewControllers/CreateReturnToBrowserViewController.swift, EduID/Resources/General/en.lproj/Localizable.strings, EduID/Resources/General/nl.lproj/Localizable.strings, EduID/localizations.yaml
also refactored a small part of the `CreateReturnToBrowserViewController`
=> EDURED-150: First screen in registration flow in English visual incorrect

EduID/Flows/CreateEduID/ViewControllers/CreateEduIDEnterPersonalInfoViewController.swift, eduID/AppDelegate.swift
also in this commit: re-enabling requestButton in `CreateEduIDEnterPersonalInfoViewController` if an error alert was displayed.
=> Possible fix for notification handling when app is not active

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/localicious.yaml, EduID/Flows/CreateEduID/ViewControllers/CreateEduIDLandingPageViewController.swift
See https://github.com/phavekes/eduid-app-ios/actions/runs/5461288227 for a successful test-run
=> Automate localicious

EduID/Flows/CreateEduID/ViewControllers/CheckEmailViewController.swift, EduID/Flows/Security/PasswordResetLink/PasswordResetLinkViewController.swift
- [ ✅] I have added proper commit messages
- [✅ ] I ran the tests
- [✅ ] I provided the ticket number as PR title
- [ ✅] I have assigned the required reviewers
Back-button after sending email not working, it's now fully functional
Testes on iPhone SE and iPhone 14
=> EDURED-162: Back-button after sending not working

EduID/Flows/Activity/ActivityViewController.swift
- [ ✅] I have added proper commit messages
- [✅ ] I ran the tests
- [ ✅] I provided the ticket number as PR title
- [✅ ] I have assigned the required reviewers
For unique ID now displays now serviceInstutionGuid or an eduID number
QA requested changes
=> EDURED-172: Wrong data & activities

EduID/Flows/Security/SecurityOverviewViewController.swift, EduID/Resources/Assets.xcassets/big_plus.imageset/Vector.svg
- [ ✅] I have added proper commit messages
- [✅ ] I ran the tests
- [ ✅] I provided the ticket number as PR title
- [✅ ] I have assigned the required reviewers
Blocks on security page have the same style
Visual changes were required by Peter Havekes
no unit tests required, tested on iPhone SE
none
=> EDURED-171: Blocks on security page

EduID/Flows/CreateEduID/ViewControllers/CreateEduIDAddInstitutionViewController.swift, EduID/Flows/CreateEduID/ViewControllers/CreateEduIDEnterPersonalInfoViewController.swift, EduID/Resources/General/en.lproj/Localizable.strings, EduID/Resources/General/nl.lproj/Localizable.strings, EduID/localizations.yaml
Dates are now shown correctly, when linking institutions for the first time during the onboarding flow
=> EDURED-169: Link expiration date

EduID/Resources/General/en.lproj/Localizable.strings, EduID/Resources/General/nl.lproj/Localizable.strings, EduID/localizations.yaml
Scan QR button on landings page now says Scan like the Android app
=> EDURED-165: Sync language landing for onboarding page

EduID/Resources/General/nl.lproj/Localizable.strings, EduID/localizations.yaml
… 
Persoonlijk account gewijzigd naar Persoonlijke login landing page
=> EDURED-165-fix: Persoonlijk account gewijzigd naar Persoonlijke login landing page

EduID/Resources/General/en.lproj/Localizable.strings, EduID/Resources/General/nl.lproj/Localizable.strings, EduID/localizations.yaml
=> Sync translations with Android and web

EduID/SharedViews/ActivityControlCollapsible.swift
Datum past nu in activiteiten overzicht
=> EDURED-177: Datum past niet in activiteiten overzicht

EduID/Flows/CreateEduID/CreateEduIDCoordinator.swift, EduID/Flows/CreateEduID/ViewControllers/CreateEduIDRegistrationCheckViewController.swift, EduID/Flows/CreateEduID/ViewControllers/CreatePincodeSecondEntryViewController.swift, EduID/Flows/CreateEduID/ViewModels/CreateEduIDRegistrationCheckViewModel.swift, EduID/Flows/CreateEduID/ViewModels/CreatePincodeAndBiometricAccessViewModel.swift, EduID/Localizable.swift, EduID/Resources/General/en.lproj/Localizable.strings, EduID/Resources/General/nl.lproj/Localizable.strings, EduID/Types/ScreenType.swift, EduID/Utilities/Constants.swift, EduID/localizations.yaml, eduID.xcodeproj/project.pbxproj
Ask to remove previous registration at correct time, now a registration check is add to the flow
=> EDURED-179: Ask to remove previous registration at correct time

EduID/Flows/Home/HomeViewController.swift, EduID/Flows/Scanning/ScanCoordinator.swift, EduID/Flows/Scanning/VerifyScanResultViewController.swift, EduID/Flows/Scanning/VerifyScanResultViewControllerDelegate.swift, EduID/Flows/VerifyAuthentication/OneTimeCodeViewController.swift, EduID/Localizable.swift, EduID/Resources/General/en.lproj/Localizable.strings, EduID/Resources/General/nl.lproj/Localizable.strings, EduID/Types/ScreenType.swift, EduID/localizations.yaml, eduID.xcodeproj/project.pbxproj, eduID.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Display a screen with a one time password (OTP), if the user does not have a connection.
=> TIQR-370: One-Time-Code flow

EduID/Flows/Scanning/ScanViewController.swift
When an error occurs while scanning, an alert will be shown now. Also shows more info about the reason.
=> TIQR-371: Improve error messages, and show as alert

EduID/Flows/CreateEduID/ViewModels/CreatePincodeAndBiometricAccessViewModel.swift, EduID/Services/AppAuthController.swift, OpenAPIClient/Classes/OpenAPIs/URLSessionImplementations.swift, eduID.xcodeproj/project.pbxproj, eduID.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, eduID/AppDelegate.swift
This was due to some issues with nullability and Swift compiler optimization.
=> TIQR-377: Fix app being stuck after enabling touch ID

EduID/Flows/Security/DeleteKeyConfirmation/DeleteKeyConfirmationViewController.swift, EduID/Flows/Security/DeleteKeyConfirmation/DeleteKeyConfirmationViewModel.swift, EduID/Flows/Security/SecurityCoordinator.swift, EduID/Flows/Security/SecurityViewControllerDelegate.swift, EduID/Flows/Security/TwoFactorKeys/TwoFactorKeysViewController.swift, EduID/Flows/Security/TwoFactorKeys/TwoFactorKeysViewModel.swift, EduID/Localizable.swift, EduID/Resources/General/en.lproj/Localizable.strings, EduID/Resources/General/nl.lproj/Localizable.strings, EduID/Types/ScreenType.swift, EduID/localizations.yaml, eduID.xcodeproj/project.pbxproj
We were missing the confirmation screen for when a 2FA key is to be removed.
=> TIQR-379: Confirmation screen for removal of 2FA key

EduID/Flows/CreateEduID/CreateEduIDCoordinator.swift, EduID/Flows/Home/MainCoordinator.swift, EduID/Flows/Scanning/ScanCoordinator.swift, EduID/Flows/Scanning/ScanViewController.swift, EduID/Types/ScreenType.swift
We determine now the scan type based on the scanned QR, instead of determining it beforehand
=> TIQR-380: Fix incorrect screen shown when scanning enrolment QR
